changed package names, updated prestart procedure to share more b/n the deb and snap

diff --git a/pkgsrc/render-json-config b/pkgsrc/render-json-config
--- a/pkgsrc/render-json-config
+++ b/pkgsrc/render-json-config
@@ -1,12 +1,12 @@
 #!/bin/bash -e
 
 if [[ $# -lt 2 ]]; then
-  (>2 echo "Required args: <input_file> <output_file>")
+  (>&2 echo "Required args: <input_file> <output_file>")
   exit 1
 fi
 
 if [[ ! -e "$1" ]]; then
-  (>2 echo "Unspecified but required argument (source file) or unable to read source file $1")
+  (>&2 echo "Unspecified but required argument (source file) or unable to read source file $1")
   exit 1
 fi
 
