differentiate dists

diff --git a/continuous_delivery/bin/watch-build b/continuous_delivery/bin/watch-build
--- a/continuous_delivery/bin/watch-build
+++ b/continuous_delivery/bin/watch-build
@@ -41,44 +41,42 @@ function clone_prj() {
       make distclean git_repo_prefix=https://github.com/open-horizon)
   fi
 
-  local artifacts=""
-  (cd $prj_dir && \
-    DIST_RELEASE="$(make show-packages | xargs -n1 | grep -oP "dist/.*~\K([^_]+)" | sort | uniq | xargs)" && \
-    VERSION=$(cat ./VERSION) && \
-    ARCH=$(./tools/arch-tag))
+  VERSION="$(cat ./VERSION)"
+  ARCH="$(./tools/arch-tag)"
+  DIST_RELEASE="$(cd $prj_dir && make show-packages | xargs -n1 | grep -oP "dist/.*~\K([^_]+)" | sort | uniq | xargs)"
 }
 
+# an empty return is an error
 function artifact_versions() {
   url="$1"
 
   # single line of versions published, like this: "2.0.10b 2.0.7 2.0.9"
-  packages=$(curl -s "${url}" | gunzip | grep -oP 'Version: \K([^~]+)' | sort | uniq | xargs)
-  if [[ $? != 0 ]]; then
+  pkgs=$(curl -sf "${url}" 2> /dev/null)
+  if [[ $? == 22 ]]; then
+    echo "-99"
+  elif [[ $? > 0 ]]; then
     (>&2 echo "Failed to determine existing deb package versions.")
     echo ""
   else
-    echo "$packages"
+    echo $pkgs | gunzip | grep -oP 'Version: \K([^~]+)' | sort | uniq | xargs
   fi
 }
 
-function build() {
-  packages="${@:1}"
+function build_publish() {
+  dist="$1"
+  rel="$2"
+  versions="${@:3}"
 
-  echo "$packages" | grep -q "$VERSION"
+  echo "$versions" | grep -q "$VERSION"
   if [[ $? != 0 ]]; then
-    echo "$VERSION not yet indexed for our architecture (determined by examining $packagesgz_url). Building package and submitting it to queue."
+    echo "$VERSION not yet indexed for our architecture ($ARCH). Building package and submitting it to queue."
     (cd $prj_dir && \
-      mkdir bld && \
+      mkdir -p bld && \
       echo "GOPATH_CACHE=/root/go/.cache" > bld/anax-rules.env && \
-
-      make packages git_repo_prefix=https://github.com/open-horizon anax-ui-branch=build_speedup anax-branch=build_speedup verbose=y && \
-      for dist in $(make show-distribution-names); do rsync -avz -f"- */" --progress --stats ${prj_dir}/dist/*${dist}* "${publish_destination_stub}${dist}"; done)
-
-    local post_build_sleep_s=5
-    echo "Pushed all packages for indexing, sleeping for ${post_build_sleep_s}s to prevent rebuilding before indexing queue is processed"
-    sleep $post_build_sleep_s
+      make mostlyclean $(make show-packages | xargs -n1 | grep "$rel" | xargs) git_repo_prefix=https://github.com/open-horizon anax-ui-branch=build_speedup anax-branch=build_speedup verbose=y && \
+      for dist in $1; do rsync -avz -f"- */" --progress --stats ${prj_dir}/dist/*${dist}* "${publish_destination_stub}${dist}"; done)
   else
-    echo "$newest_pkg already indexed for our architecture (determined by examining $packagesgz_url)."
+    echo "$newest_pkg already indexed for our architecture ($ARCH)."
   fi
 }
 
@@ -87,16 +85,19 @@ while true; do
 
   clone_prj
 
-  for dr in "${DIST_RELEASE}"; do
-    echo "Processing $dr"
-    draddr=""
-
-    echo "$draddr"
-
+  for dr in ${DIST_RELEASE}; do
     IFS='.' read -ra draddr <<< "$dr"
-    echo "**** $draddr ****"
     vers=$(artifact_versions $(echo "$packagesgz_url_templ" | sed "s,##DIST##,${draddr[0]},g" | sed "s,##RELEASE##,${draddr[1]},g" | sed "s,##ARCH##,${ARCH},g"))
-
-    echo "** $vers **"
+    if [[ $vers == "" ]]; then
+      # TODO: add a backoff, we had a failure getting to the service
+      (>&2 echo "Failed to build, backing off.")
+      sleep 10m
+    else
+      build_publish "${draddr[0]}" "${draddr[1]}" "$vers"
+    fi
   done
+
+  local post_build_sleep_s=5
+  echo "Pushed all packages for indexing, sleeping for ${post_build_sleep_s}s to prevent rebuilding before indexing queue is processed"
+  sleep $post_build_sleep_s
 done
